#!/bin/bash
INFLUX_PASS=$(openssl rand -base64 16)
INFLUX_TOKEN=$(openssl rand -hex 16)
GRAFANA_PASS=$(openssl rand -base64 12)
MIKROTIK_PASS=$(openssl rand -base64 12)
export INFLUX_PASS INFLUX_TOKEN GRAFANA_PASS MIKROTIK_PASS
docker-compose up -d
