#!/bin/bash

# Generate random passwords
INFLUX_PASS=$(openssl rand -base64 16)
INFLUX_TOKEN=$(openssl rand -hex 16)
GRAFANA_PASS=$(openssl rand -base64 12)
MIKROTIK_PASS=$(openssl rand -base64 12)

# Export variables for Docker Compose
export INFLUX_PASS INFLUX_TOKEN GRAFANA_PASS MIKROTIK_PASS

# Run Docker Compose
docker-compose up -d
